### ISSUE TITLE
ошибка при загрузки фото

### ISSUE THREAD

**Issue by yo8z6gv** [fiftythreecorp/VKPhotoLoader#4]
PS E:\D\B\Ch\Pr1\VKPhotoLoader-master (1)\VKPhotoLoader-master> node loader.js
internal/modules/cjs/loader.js:1131
    throw err;
    ^

SyntaxError: E:\D\B\Ch\Pr1\VKPhotoLoader-master (1)\VKPhotoLoader-master\config.json: Unexpected token O in JSON at position 133
    at parse (<anonymous>)
←[90m    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1128:22)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:950:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:790:14)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:974:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:92:18)←[39m
    at Object.<anonymous> (E:\D\B\Ch\Pr1\VKPhotoLoader-master (1)\VKPhotoLoader-master\loader.js:5:14)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1085:14)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:950:32)←[39m
PS E:\D\B\Ch\Pr1\VKPhotoLoader-master (1)\VKPhotoLoader-master>

**Comment by yo8z6gv** [comment]
@Rast1234 не знаешь, существуют ли способы для загрузки в вк много картинок без вызова капчи?
может какая мобильная версия, или как здесь пишут про какой-то апи?
или это невозможно?

раньше помню грузил [50к фотографий](https://vk.com/shoutai) только за счет старой капчи, где надо было вводить 5 англ. символов с цифрами и все. сейчас же это гугл и чем чаще капча гугла, тем сложнее она становится: в начале просто нажал и все - прошел капчу, затем выбираешь картинки, после будет уже 2-3 страницы выбора картинок, а после вообще что бы ни выбрал всегда будет провальное. к тому же капча фиксированно вызывается каждые 50 картинок, а за раз можно 200 выкинуть.
раньше можно было за раз выкинуть неограниченно, пока браузер не крашнется, таким образом достаточно было одной страницы и все картинки были в правильном порядке, с пропуском картинки на вводе капчи. сейчас же надо открыть несколько страниц и загружать в каждом, так обойдешь лимит в одновременную загрузку, однако столкнешься с проблемой последовательности загрузки.

если писать по похожим словам, поисковик выдает сомнительную [альтернативу](https://chaldaev.pro/vkphotoloader-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B0-%D0%B4%D0%BB%D1%8F-%D0%BC%D0%B0%D1%81%D1%81%D0%BE%D0%B2%D0%BE%D0%B9-%D0%B7%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B8/690/) от chaldaev. но там помимо того что платно, так еще и какой-то левый софт для временной генерации какого-то номера, какая-то привязка (защита от пиратсва) и вообще непонятно как все это будет работать.

upd: оказывается вк вернул старую капчу, однако даже с ней проблемы новшества остаются: ограничение скорости при загрузке картинок; лимит в разовую загрузку 200шт.
на телефоне в последней версии [оф. приложения ВК](https://play.google.com/store/apps/details?id=com.vkontakte.android&hl=ru&gl=US) можно выбрать 100 картинок. капча не вызывается в процессе загрузки всей сотни.


--
старая капча
![image](https://user-images.githubusercontent.com/62700253/126550280-df84df1d-47f0-4c12-98b1-5cb3fb6a95f3.png)

**Comment by Rast1234** [comment]
Никогда не занимался загрузкой в вк, только скачиванием. Но полюбому есть api, может быть открытый, может быть закрытый, с токеном приложения vk. На апи распространяется рейт лимит, просто надо делать не слишком много запросов за единицу времени. Апи у вконтакта можно посмотреть на самом вконтакте, либо глянуть реализацию типа VKNet

**Comment by Rast1234** [comment]
например моя поделка, voffline, скачивает тысячи фоток/постов/треков без капчи

**Comment by yo8z6gv** [comment]
@Rast1234  фига ты быстро ответил)) не успел я отвлечься, а ты уже тут))
кароче, в основном мне это надо для форумов. тк в вк грузит картинку и превью. то было бы удобно создавать торрент раздачи с указанием фотохостинга от вк, или просто куда-нибудь прикреплять, где не поддерживаются пикчи от сервера-форума(такие практически все форумы). так и сразу можно выбрать нужное превью-масштабирование)) старый формат ссылки до сих пор работает, хотя есть и новый - 
https://sun9-26.userapi.com/impf/c845122/v845122115/1b314a/H1eCr53ZLQA.jpg?size=1000x1435&quality=96&sign=956edf93794cbeae8dfd08360eb732ef&type=album
старый будет без
"sun9-49" изменить на "pp"
"/impg" удалить
и удалить все после "?", включая "?"
выглядеть так:
https://pp.userapi.com/c845122/v845122115/1b314a/H1eCr53ZLQA.jpg

upd проверил по новому формату и там нет картинки о_О; видимо вновь недавно что-то изменили. однако по новому формату с sign по прежнему работают ссылки от 5 апреля, т.е по крайне мере уже как 3 месяца точно. потихоньку веду отчет, просматривая с тор, чтобы наверняка без авторизации и как будет со стороны))
ps upd; оказывается я неправильно ссылку отформатировал. старый формат работает.. прост я кривой

http://sun9-54.userapi.com/impg/eONoNK2I-hAotJQuVG2oeLvGOL0wd0OJyflePA/wd9NfRmArqA.jpg?size=300x300&quality=96&sign=6936a3941fd561360af6fc314319f9ac&type=album

вот касательно превью:
https://sun9-26.userapi.com/impf/c845122/v845122115/1b314a/H1eCr53ZLQA.jpg?size=1000x1435&quality=96&sign=956edf93794cbeae8dfd08360eb732ef&type=album
https://sun9-26.userapi.com/impf/c845122/v845122115/1b314a/H1eCr53ZLQA.jpg?size=753x1080&quality=96&sign=877d91bc9734e921d9ad28b8822697af&type=album
https://sun9-26.userapi.com/impf/c845122/v845122115/1b314a/H1eCr53ZLQA.jpg?size=562x807&quality=96&sign=c400f5811495df5aea6d5d3553781e05&type=album
https://sun9-26.userapi.com/impf/c845122/v845122115/1b314a/H1eCr53ZLQA.jpg?size=421x604&quality=96&sign=bd829f30cc0a8266f1b19885edb3085c&type=album

**Comment by yo8z6gv** [comment]
@Rast1234 прост гугл недавно дообновился и теперь абсолютно все занимает место: гугл.документы, гугл.фото, не уверен, но возможно и bloger, хотя там не поддерживается даже разрешение 1920х1080. но там тоже оч удобно превью делается))

знаю что соц сетях даже если удалить фотку, она по прежнему будет на серверах и доступна. правда хз от чего эти "sign" берутся. и жалко что vkopt https://raw.githubusercontent.com/VkOpt/VkOpt/master/builds/vkopt_script.user.js или flyvk https://openuserjs.org/meta/flyink13/FlyVK.meta.js не обновятся и не починят "поиск по картинке", т.к все сервисы iqdb.org, tineye.com вводят ссылку ДО &quality... видимо символом "&" стоит ограничение до какого копировать

**Comment by yo8z6gv** [comment]
@Rast1234  скачивать картинки из вк слишком просто и абсолютно все может. даже в самом интерфейсе есть кнопка "оригильнаое изображение". 
начиная от узкоспециализированных скриптов выше о которых я упомянул [vkopt](https://raw.githubusercontent.com/VkOpt/VkOpt/master/builds/vkopt_script.user.js), [flyvk](https://openuserjs.org/meta/flyink13/FlyVK.meta.js). заканчивая тем же savefrom https://download.sf-helper.com/chrome/helper.meta.js или [vkmusic](https://vkmusic.citynov.ru/)
а вот чего-то с помощью чего можно загрузить уже нету. хотя все социальные сети отличные площадки для размещения картинок. вк же еще подходит и для файлов, правда поскольку файлы крупные и можно так разместить сотни гб, то это палевнее, чем пикчи)) к тому же с файлами просто пофиксеть, а вот пикч у всех соц-сетей можно прямую ссылку вытащить и всем пофиг. причем сам вк думаю об этом знает

отпиши если есть какие идеи или нет. ты прост единственный кто как-то реагирует и возможно разбирается в том как это работает

**Comment by Rast1234** [comment]
Ты смотрел то, о чем я написал? Вот например загрузка фото через vkNet - пробуй) https://vknet.github.io/vk/photos/save/

**Comment by yo8z6gv** [comment]
@Rast1234 я хз как это использовать)
запустил PowerShell, в нем написал "Install-Package VkNet":
![1](https://user-images.githubusercontent.com/62700253/126606201-1c743a9b-3e76-438e-baf8-67dcbc428edc.jpg)
нажал Y и после что-то загрузилось за 1 секунду, теперь в "Get-PackageSource"
![3](https://user-images.githubusercontent.com/62700253/126606266-f62bf692-2d44-4de2-a082-f17c3bf717b0.jpg)
по директории "%LOCALAPPDATA%\PackageManagement\ProviderAssemblies" валяется файл "nuget\2.8.5.208\Microsoft.PackageManagement.NuGetProvider.dll"
и на "Install-Package VkNet":
![2](https://user-images.githubusercontent.com/62700253/126606293-6f16b037-c70e-41a6-be09-e556f2af37bd.jpg)
не говоря уже о втором пункте установке:
![4](https://user-images.githubusercontent.com/62700253/126606335-0e99ad86-4333-4c11-92d7-0071a8531cec.jpg)
или после установки https://dotnet.microsoft.com/download/dotnet/5.0 Installers win64 5.0.8 там похожее сообщение:
![5](https://user-images.githubusercontent.com/62700253/126606573-756f1928-30a2-47f9-92b7-13de0199122b.jpg)
так что на самом первом пункте не понял что делаю не так, не говоря уже о попытках авторизации вк и прочего..

**Comment by Rast1234** [comment]
powershell тут ни при чем. VkNet это либа для .net, надо писать приложение, на C# например.
но это пофиг, главное-то что там есть функциональность загрузки фоток, значит и у других есть, либо можно посмотреть как работает и сделать аналогично, если в твоей экосистеме нет готового.

**Comment by yo8z6gv** [comment]
@Rast1234 что за "надо писать приложение", мне ведь не нужно приложение. разве нельзя просто указать папку через консоль и попросить загружать используя vknet? и какого формата должен быть запрос. поэтому и использую powershell

>либа для .net, надо писать приложение, на C# например

это ты говоришь типо о https://www.youtube.com/watch?v=9RRXJVAVa60 , где надо через Microsoft Visual Studio оформлять, потом каждый блок связывать в .cs .. но это ведь лишние действия. к каждой функции обратиться через powershell разве нельзя?

 
>если в твоей экосистеме нет готового

у меня вообще нет никаких экосистем.. у всех рандомных челиков не будет никаких "экосистем")

**Comment by Rast1234** [comment]
у тебя какая-то своя атмосфера...

> разве нельзя просто указать папку через консоль и попросить загружать используя vknet

нет, нельзя. повершел тебе вообще никак не поможет. это либа для шарпа, а не набор функций для командной строки.

>  в .cs .. но это ведь лишние действия. к каждой функции обратиться через powershell разве нельзя?

окей, технически из повершела это возможно, но кода придется написать больше, чем то, что ты считаешь "лишними действиями". еще и огрести сложностей по пути, поэтому так никто не делает.

> у меня вообще нет никаких экосистем.. у всех рандомных челиков не будет никаких "экосистем")

давай уточню. вот ты пишешь на ноде, на JS (судя по этому репозиторию). это и есть твоя экосистема. ты пакеты из NPM берешь. там для тебя полюбому найдется пакет который реализует VK API, и у него будет метод загрузки и сохранения фотографии. если не хочешь юзать готовый пакет, либо раскури как он работает и скопируй себе, либо пиши реализацию сам, читая доку VK API. что тут непонятного-то... ты спросил как загружать, я тебе дал пример и концепции объяснил, но походу ты не хочешь найти и адаптировать существующие решения, и не хочешь сам разбираться, тогда что ты хочешь то?)))

**Comment by Rast1234** [comment]
а ну я кажется понял, ты хочешь типа готовый скрипт или прилагу чтобы дать ей пачку фоток и запустить, пусть оно загружает. ну я точно таких не знаю. те что ты нашел видимо не подошли. тогда тебе точно придется код писать самому, чтобы делал именно то что нужно тебе. есть библиотеки для API вконтакта, под любой язык/экосистему.
